### ISSUE TITLE
Weird URL Created

### ISSUE THREAD

**Issue by simonv3** [theodi/panopticon#113] opened 2015-04-10 03:46 UTC
The weird duplicate URL issue happens when I roll www-frontend, publisher, and content_api back to before I made the changes (for lack of a better idea on what could be causing this). 

I tested this by creating an Artefact in Panopticon, choosing “Event” “Lunchtime Lecture [lunchtime-lecture]”, and then adding “lunchtime-lecture” as a keyword at the bottom in Panopticon.

Then click on "Save and go to item", and in Publisher click on "Preview". 

The URL is: 

```
http://www.dev/lunchtime-lectureslunchtime-lectures/test-rolled-back-content-api?utf8=%E2%9C%93&cache=1428637092&edition=1&commit=Preview
```

Note the double lunchtime-lectures in the URL. Not adding the keyword in Panopticon creates a well-formated URL.

I tested this on both HEAD for content_api, publisher, and www, as well as theodi/publisher@edaa30f8f501c83adb347ad27bd69b3c6113929b, theodi/content_api@19a6ac3f737c1fbe8cd01abd0739a6b1fc23814e, and theodi/frontend-www@c9ea80a70d41dc46b5f3c2373e7b1728ba0b45ad (ie, before the keyword changes were made).

**Comment by langphil** [comment] 2015-04-13 13:35
So, this was previously an issue with Panopticon. Where you selected a page type "Event" and then selected a secondary type "Lunchtime Lecture". What happens, for some reason is when you save the Panopticon artefact and move to publisher, "Lunchtime Lecture" is added twice as a a secondary type. If you go back into the Panopticon artefact and remove the extra one, the page then previews fine.

No idea why it does this.

This only affects the preview in Publisher as far as I am aware. If you publish, it's not an issue and the URL works fine. I could be wrong here.

The issue is that, since the tagging update we've lost the ability to edit fields in Panopticon and Publisher and thus can no longer go back in and remove the extra attribute.

We need to bring back the ability to make edits to all fields in the Panopticon and Publisher stages after an artefact has been published.

**Comment by Floppy** [comment] 2015-04-14 15:33
Does this happen for anything, or only lunchtime lectures with the lunchtime-lecture tag? I suspect there's an array of tag IDs that's being used somewhere in the URL generation, and because the type and the tag have the same string in them, it's using both flattened together.

**Comment by Floppy** [comment] 2015-04-14 16:05
Found, replicated, and fixed in https://github.com/theodi/odi_content_models/issues/75

**Closed** 2015-04-14 16:18 UTC
